### ISSUE TITLE
error compile gatsby files

### ISSUE THREAD

**Issue by afreisinger** [datawookie/docker-gatsby#2]
Hi  @datawookie ! 

I'm new to gatsby, and i have a problem
I followed all the steps in the quick start guide, on [but](https://datawookie.dev/blog/2023/04/developing-a-gatsby-site-with-docker/), I receive the following error:

```
git clone git@github.com:gatsbyjs/gatsby-starter-default.git
cd gatsby-starter-default
docker run -it -p 8000:8000 -v ${PWD}:/site --name gatsby datawookie/gatsby:latest
```
This is the error:

```
⠏ compile gatsby files
/site/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Initiated Worker with invalid execArgv flags: --no-opt
    at new Worker (node:internal/worker:222:13)
    at ThreadsWorker.start (/site/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:51:19)
    at Worker.fork (/site/node_modules/@parcel/workers/lib/Worker.js:105:23)
    at WorkerFarm.startChild (/site/node_modules/@parcel/workers/lib/WorkerFarm.js:248:12)
    at WorkerFarm.startMaxWorkers (/site/node_modules/@parcel/workers/lib/WorkerFarm.js:420:14)
    at new WorkerFarm (/site/node_modules/@parcel/workers/lib/WorkerFarm.js:149:10)
    at createWorkerFarm (/site/node_modules/@parcel/core/lib/Parcel.js:568:10)
    at Parcel._init (/site/node_modules/@parcel/core/lib/Parcel.js:232:20)
    at Parcel.run (/site/node_modules/@parcel/core/lib/Parcel.js:273:7)
    at Object.runParcel (/site/node_modules/gatsby/src/utils/parcel/compile-gatsby-files.ts:66:27) {
  code: 'ERR_WORKER_INVALID_EXEC_ARGV'
}

Any idea ?
Thanks
REgards

Adrian

**Comment by datawookie** [comment]
Hi @afreisinger, thanks for the issue. I am unable to replicate the problem. I have executed the following:

1. Get a fresh copy of the starter project.

```
git clone git@github.com:gatsbyjs/gatsby-starter-default.git
```

2. Move into the project directory.

```
cd gatsby-starter-default/
```

3. Build and serve the site.

``` 
docker run -it -p 8000:8000 -v ${PWD}:/site datawookie/gatsby:latest
```

After a short while the site is available at http://127.0.0.1;8000.

Is this the precise procedure that you followed or did you do something else? What hardware are you running on?

Best regards, Andrew.

![image](https://github.com/user-attachments/assets/cb268e1c-bc43-41ae-bdb7-8da6d00a0501)

**Comment by afreisinger** [comment]
Hi @datawookie  !Indeed, I followed the procedure you described and I am using a MacBook Air 2020, Sonoma 14.5. 
Regards !
Adrian

**Comment by datawookie** [comment]
Hmmm. I'll be honest, I'm a long time Linux user and don't know much about the Mac. Have you tried pulling this repository and building the image yourself? Perhaps this is an architecture thing?

**Comment by datawookie** [comment]
Another thought: do you have a `node_modules` folder in your project? If so, try to delete that before running the image.

**Comment by afreisinger** [comment]
I resolved it by building it with multi-platform support.
```
IMAGE = afreisinger/gatsby
PLATFORMS = linux/amd64,linux/arm64
NODE_VERSION = $(shell grep "^FROM" Dockerfile | head -n 1 | sed 's/.*://;s/-.*//')
IMAGE_LATEST = $(IMAGE):latest
IMAGE_VERSION = $(IMAGE):$(NODE_VERSION)

.PHONY: all
all: build

.PHONY: build
build:
	@echo "Starting Docker build..."
	@echo "Building Docker image for platforms: $(PLATFORMS) with tags: $(IMAGE_LATEST) and $(IMAGE_VERSION)"
	@if ! docker buildx inspect dev-builder >/dev/null 2>&1; then \
		docker buildx create --name dev-builder; \
		docker buildx use dev-builder; \
		docker buildx inspect --bootstrap; \
	fi
    # docker buildx build --platform $(PLATFORMS) -t $(IMAGE_LATEST) -t $(IMAGE_VERSION) --progress=plain --output=type=local,dest=./output .
	docker buildx build --platform $(PLATFORMS) -t $(IMAGE_LATEST) -t $(IMAGE_VERSION) --progress=plain --push .

.PHONY: build-no-cache
build-no-cache:
	@echo "Starting Docker build..."
	@echo "Building Docker image for platforms: $(PLATFORMS) with tags: $(IMAGE_LATEST) and $(IMAGE_VERSION)"
	@if ! docker buildx inspect dev-builder >/dev/null 2>&1; then \
		docker buildx create --name dev-builder; \
		docker buildx use dev-builder; \
		docker buildx inspect --bootstrap; \
	fi
	docker buildx build --platform $(PLATFORMS) -t $(IMAGE_LATEST) -t $(IMAGE_VERSION) --progress=plain --no-cache .

.PHONY: push
push:
	@echo "Pushing Docker image $(IMAGE_LATEST) and $(IMAGE_VERSION) to registry..."
	docker push $(IMAGE_LATEST)
	docker push $(IMAGE_VERSION)

.PHONY: clean
clean:
	@echo "Removing buildx builder"
	docker buildx rm dev-builder

.PHONY: rebuild
rebuild: clean build
```

**Comment by datawookie** [comment]
Brilliant. Thanks for that. I have updated the `README` and pointed to this issue as the solution for Mac.
